{
    'name': 'Recepción de Materiales MP',
    'version': '19.0.2.1.2',
    'summary': 'Inspección de entrada, criterios de aceptación, destino automático y firma con PIN',
    'category': 'Inventory',
    'author': 'Amunet',
    'depends': ['amunet_lot', 'stock', 'amunet_quality', 'product', 'amunet_equipment_calibration'],
    'data': [
        'data/seeds_20260901_165910.xml',
        'security/ir.model.access.csv',
        'data/cron_reorder_notify.xml',
        'wizard/recepcion_pin_wizard_views.xml',
        'wizard/amunet_lot_serial_split_wizard_views.xml',
        'wizard/amunet_reception_serial_wizard_views.xml',
        'reports/report_recepcion_materiales.xml',
        'views/product_category_views.xml',
        'views/product_template_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_lot_alert_views.xml',
        'views/stock_lot_views.xml',
        'views/stock_lot_inspeccion_equipos_views.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
