
services:
  # 1. La Base de Datos (Postgres)
  web-db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data # Esto guarda los datos aunque apagues la PC

  # 2. La Aplicación (Odoo)
  web:
    image: odoo:19.0  # <--- CAMBIA ESTO si usas otra versión (ej. odoo:17.0)
    depends_on:
      - web-db
    ports:
      - "8069:8069"   # El puerto para entrar desde el navegador
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons  # <--- MAGIA: Conecta tu carpeta local con el Odoo virtual
      - ./filestore:/var/lib/odoo/filestore
    environment:
      - HOST=web-db
      - USER=odoo
      - PASSWORD=odoo

volumes:
  odoo-web-data:
  odoo-db-data: