[options]
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$lbJ2LoUwBoBQqhVijFGKcQ$8ENs7qz0QJY9Z..kp2WrW6deWt8/MxkK3SOFbh4Rd1uVNdGFxR.DgyhVvqzAjvhwKKeiB677auE8h/9tB/Fudw
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/opt/odoo/custom
data_dir = /var/lib/odoo
logfile = /var/log/odoo/odoo-server.log
log_level = warn
proxy_mode = True
workers = 2
