# -*- coding: utf-8 -*-
{
    'name': 'Amunet - Control de Cambios General',
    'summary': 'Control de cambios para formatos, manuales e infraestructura',
    'description': 'Registro de control de cambios general: formatos, manuales, instalaciones y equipos. ISO 13485 / NOM-241.',
    'author': 'Amunet',
    'category': 'Quality',
    'version': '19.0.1.0.0',
    'depends': ['mail', 'amunet_documentos'],
    'data': [
        'security/amunet_cc_general_security.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/lang_week_start.xml',
        'wizard/amunet_cc_rechazo_wizard_views.xml',
        'views/amunet_cc_general_views.xml',
        'views/amunet_documento_ext_views.xml',
        'views/mis_pendientes_dashboard_action.xml',
        'views/auditorias_hub_action.xml',
        'views/programas_hub_action.xml',
        'views/menus.xml',
        'reports/report_cc_anual.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'amunet_cc_general/static/src/css/cc_general.css',
            'amunet_cc_general/static/src/js/weekend_datepicker.js',
            'amunet_cc_general/static/src/js/mis_pendientes_dashboard.js',
            'amunet_cc_general/static/src/xml/mis_pendientes_dashboard.xml',
            'amunet_cc_general/static/src/js/auditorias_hub.js',
            'amunet_cc_general/static/src/xml/auditorias_hub.xml',
            'amunet_cc_general/static/src/js/programas_hub.js',
            'amunet_cc_general/static/src/xml/programas_hub.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
