{
    'name': 'Documentación Técnica (Amunet)',
    'version': '19.0.2.0.0',
    'category': 'Quality',
    'summary': 'Gestión de manuales técnicos y revisión cruzada entre Validación y Calidad',
    'author': 'Amunet',
    'website': 'https://www.amunet.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/doc_carpeta_views.xml',
        'views/doc_compartida_views.xml',
        'views/doc_revision_wizard_views.xml',
        'views/doc_reemplazo_wizard_views.xml',
        'views/doc_revision_historial_views.xml',
        'views/doc_reopen_wizard_views.xml',
        'views/doc_tomar_wizard_views.xml',
        'views/doc_actualizar_wizard_views.xml',
        'views/menus.xml',
        'data/carpetas.xml',
        'data/cron_revision.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
