from . import doc_carpeta
from . import doc_compartida
from . import doc_revision_wizard
from . import doc_reemplazo_wizard
from . import doc_revision_historial
from . import doc_reopen_wizard
from . import doc_tomar_wizard
from . import doc_actualizar_wizard
from . import doc_firma_wizard
